"""Pydantic models for the Backlog Synthesizer pipeline."""

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class RequirementType(str, Enum):
    feature = "feature"
    bug = "bug"
    improvement = "improvement"
    tech_debt = "tech_debt"
    nfr = "nfr"


class Granularity(str, Enum):
    epic = "epic"
    story = "story"
    task = "task"


class Confidence(str, Enum):
    high = "high"
    medium = "medium"
    low = "low"


class CheckType(str, Enum):
    overlap = "overlap"
    duplicate = "duplicate"
    architecture = "architecture"
    prior_decision = "prior_decision"
    dependency = "dependency"
    priority = "priority"
    no_epic = "no_epic"
    new_epic = "new_epic"
    nfr_violation = "nfr_violation"
    ambiguity = "ambiguity"


class GroundingStatus(str, Enum):
    valid = "valid"
    warning = "warning"
    invalid = "invalid"


class Actionability(str, Enum):
    high = "high"
    medium = "medium"
    low = "low"


# ---------------------------------------------------------------------------
# Core models
# ---------------------------------------------------------------------------

class AmbiguityFlag(BaseModel):
    description: str
    question: str
    severity: str = "medium"  # low | medium | high


class PrioritySignal(BaseModel):
    signal: str
    urgency: str = "medium"  # low | medium | high | critical
    deadline: Optional[str] = None


class Priority(str, Enum):
    critical = "critical"
    high = "high"
    medium = "medium"
    low = "low"


class Requirement(BaseModel):
    """A single requirement extracted from the meeting transcript."""
    id: Optional[str] = None
    description: str
    source_citation: str = Field(..., description="Exact quote from transcript")
    speaker: str = Field("", description="Who said it (e.g. 'Sarah (PM)'), or 'Unknown' if unclear")
    type: RequirementType
    granularity: Granularity
    priority: Priority = Priority.medium
    priority_signals: list[PrioritySignal] = Field(default_factory=list)
    ambiguity_flags: list[AmbiguityFlag] = Field(default_factory=list)
    confidence: Confidence = Confidence.medium


class Check(BaseModel):
    """A check raised during cross-referencing."""
    id: Optional[int] = None
    story_title: str
    check_type: CheckType
    details: str
    confidence: Confidence = Confidence.medium
    proposed_resolution: Optional[str] = None
    routed_to: Optional[str] = None  # PM | Architect | Dev Lead
    related_item_id: Optional[str] = None  # e.g. ERIS-042


class CandidateStory(BaseModel):
    """A candidate user story generated by the synthesizer."""
    id: Optional[int] = None
    title: str
    description: str
    type: RequirementType
    acceptance_criteria: list[str] = Field(default_factory=list)
    feature_tags: list[str] = Field(default_factory=list)
    priority_signals: list[PrioritySignal] = Field(default_factory=list)
    priority: Optional[str] = None  # critical | high | medium | low | None (undefined)
    confidence: Confidence = Confidence.medium
    source_citation: str = ""
    speaker: str = ""
    epic_id: Optional[str] = None  # existing epic external_id
    proposed_epic: Optional[str] = None  # proposed epic name if no existing match
    checks: list[Check] = Field(default_factory=list)
    questions: list[RoutedQuestion] = Field(default_factory=list) if False else Field(default_factory=list)
    grounding_status: Optional[GroundingStatus] = None
    grounding_issues: list[str] = Field(default_factory=list)


class RoutedQuestion(BaseModel):
    """A question routed to a specific role."""
    question: str
    routed_to: str  # PM | Architect | Dev Lead
    context: str = ""


# Re-declare CandidateStory.questions with the correct type now that
# RoutedQuestion is defined.
CandidateStory.model_fields["questions"].default_factory = list  # type: ignore[attr-defined]


class EpicProposal(BaseModel):
    """A proposal for a new epic."""
    title: str
    goal: str
    scope: str
    justification: str = Field(..., description="Why existing epics don't fit")
    confidence: Confidence = Confidence.medium
    story_titles: list[str] = Field(default_factory=list)


class ReviewDecision(BaseModel):
    """A human review decision for a story."""
    story_title: str
    decision: str  # confirmed | rejected | modified
    rationale: Optional[str] = None
    modifications: Optional[dict] = None  # field -> new_value


class ValidationResult(BaseModel):
    """Grounding validation result for a single story."""
    story_title: str
    grounding_status: GroundingStatus
    issues: list[str] = Field(default_factory=list)
    suggested_fix: Optional[str] = None


class MeetingQuality(BaseModel):
    """Meeting quality feedback produced by the synthesizer."""
    total_requirements: int = 0
    ambiguous_count: int = 0
    ambiguity_ratio: float = 0.0
    actionability_score: Actionability = Actionability.medium
    verbal_recommendation: str = ""


class BacklogHygieneFlag(BaseModel):
    """Flag for a potentially obsolete backlog item."""
    external_item_id: str
    flag_type: str = "potentially_obsolete"
    reason: str
    source_citation: str = ""


class PipelineError(BaseModel):
    """An error encountered during pipeline execution."""
    agent: str
    error_type: str
    message: str
    recoverable: bool = True
